image: emilerolley/maven

lib-compile:
  stage: build
  script:
    - cd paleo-lib && mvn compile

lib-test:
  stage: test
  script:
    - cd paleo-lib && mvn compile test

lib-package:
  stage: deploy
  script:
    - cd paleo-lib && mvn package install

calc-compile:
  stage: build
  script:
    - cd paleo-calc && mvn compile

calc-test:
  stage: test
  script:
    - cd paleo-calc && mvn compile test

calc-assembly:
  stage: deploy
  script:
    - cd paleo-calc && mvn compile assembly:single
